---
resources:
  - name: resource-zabbix
    type: git
    source:
      uri: https://github.com/antigenius0910/zabbix.git
      branch: release/4.0_yen

jobs:
  - name: job-test-zabbix
    public: true
    plan:
      - get: resource-zabbix
      - task: zabbix-app-tests
        file: resource-zabbix/hack/ci/task_run_tests.yml

